name: CodSpeed Benchmarks
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
permissions:
  contents: read
  id-token: write
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Rust toolchain
      uses: moonrepo/setup-rust@v1
      with:
        channel: nightly-2025-06-04
        cache-target: release
        bins: cargo-codspeed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build benchmarks
      run: cargo codspeed build
    - name: Run benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        upload-url: ${{ secrets.CODSPEED_STAGING_UPLOAD_URL }}
        mode: simulation
        run: cargo codspeed run
